version: '3.8'
services:
  backend:
    build: 
     context: ./backend
     dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tasker
      POSTGRES_CONN_STR: postgres://postgres:postgres@db:5432/tasker?sslmode=disable

  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    profiles:
      - debug

volumes:
  postgres-data:
